package com.example.blackoutmesh

import android.bluetooth.le.AdvertiseSettings
import android.bluetooth.le.ScanSettings
import java.util.UUID

object Config {
    // Our private "channel" on Bluetooth. Both phones must use the same UUIDs.
    val SERVICE_UUID: UUID = UUID.fromString("6e0b1a10-7b1d-4a52-9c1e-5a6f0a1d0001")
    val ALERT_CHAR_UUID: UUID = UUID.fromString("6e0b1a10-7b1d-4a52-9c1e-5a6f0a1d0002")

    // Generated by make_packet.py
    const val PUBLIC_KEY_HEX = "9d2b0f035fd0feebcd89cc5eed8695163832cfc0b79388c1007b6ee15ed71d34"
    const val SEED_PACKET_HEX = "01f0c1fdbb6ac102410078000100023e40d822df5dc81ff019bc889633b9f4e68c30ac94db883f9b02db92f1555ab9b6a4b211cb697ce81feb2983662c895a540f8cfb502fa34872430cdf646f7f05"

    // Background-safe scanning. SCAN_MODE_BALANCED prevents Android's 30-minute background scan ban
    // while providing fast discovery cycles and low battery drain.
    const val SCAN_MODE = ScanSettings.SCAN_MODE_BALANCED
    const val ADVERTISE_MODE = AdvertiseSettings.ADVERTISE_MODE_BALANCED

    // Re-check interval for the same broadcaster/peer device (6s for fast update reception)
    const val REFETCH_COOLDOWN_MS = 6_000L

    // Ask for a bigger Bluetooth message size so the 79-byte packet fits in one read
    const val MTU = 185

    // Give up on a fetch that takes longer than this
    const val FETCH_TIMEOUT_MS = 10_000L

    val PUBLIC_KEY: ByteArray get() = AlertCodec.hex(PUBLIC_KEY_HEX)
}
